# Generated by Django 5.1.1 on 2024-10-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('utilities', 'Utilities'), ('salaries', 'Salaries'), ('maintenance', 'Maintenance')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('rooms', models.ManyToManyField(blank=True, related_name='expenses', to='Hotel.room')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=50)),
                ('expense_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('income_budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expenses', models.ManyToManyField(blank=True, related_name='budgets', to='Hotel.expense')),
                ('incomes', models.ManyToManyField(blank=True, related_name='budgets', to='Hotel.income')),
            ],
        ),
    ]
