# Generated by Django 5.1.1 on 2024-10-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hotel', '0003_alter_hotel_capacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hotel_id',
            new_name='hotel',
        ),
    ]
